Create game-streaming vertical page
canonical-web-and-design/anbox-cloud.io pull request #172
Opened 2021-05-19 08:31 UTC by petesfrench

## Done

- Create game-streaming vertical page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/gaming
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare against [Copy-doc](https://docs.google.com/document/d/1c9WcMRx1OlQxUntC6YF5oq_wjmwA5vI-RDZC926EYmo/edit#)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4009

2021-05-19 08:31 UTC, webteam-app commented
Demo starting at https://anbox-cloud-io-172.demos.haus

2021-05-19 09:43 UTC, anthonydillon requested changes
QA:
- [ ] Should there be navigation links to these pages?
- [ ] We use 2 spaces in HTML. Can you convert the new pages to use 2 spaces, please?

2021-05-19 09:43 UTC, anthonydillon commented on templates/telco/index.html
> +                        <p>Unlike Android emulators that make use of virtual machines, Anbox Cloud leverages system containers through LXD, the next generation system container manager. It offers a u
Missing a link to LXD.

2021-05-19 09:43 UTC, anthonydillon commented on templates/telco/index.html
> +                        <p>Streaming Android apps to thousands of mobile and desktop clients simultaneously requires orchestration and monitoring of several software components. This involves streami
Missing links here

2021-05-19 09:43 UTC, anthonydillon commented on templates/telco/index.html
> +                    <p>Get in touch with Canonical to explore avenues to deliver <br>new value-added services to millions via cloud streaming. </p>
Should'nt need a br here. Let the grid wrap the content.

2021-05-19 09:43 UTC, anthonydillon commented on templates/telco/index.html
> +                    <button class="p-button--positive">Get in touch</button>
Please use this for now: `<a href="/#request-form" class="p-button--positive">Get in touch</a>`

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +                        Learn about value-added telco services with Anbox Cloud >
Same here with removing this link

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +            <p>Unlike Android emulators that make use of virtual machines, Anbox Cloud leverages system containers through <a href="https://linuxcontainers.org/">LXD</a>, the next generation system c
Missing `p-link--external` on the LXD link

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +        <div class="col-6 p-card">
Please use to card classes

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +            <h2>A scalable infrastructure for <br /> game streaming</h2>
Let the grid wrap the text

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +            <button class="p-button--positive">Get in touch</button>
Update the link with the comment below

2021-05-19 09:43 UTC, anthonydillon commented on templates/gaming/index.html
> +            <p>Get in touch with Canonical to explore avenues to <br /> deliver your games to millions via cloud streaming. </p>
You dont need br's. Lets the grid wrap the content

2021-05-19 11:11 UTC, anthonydillon requested changes

2021-05-19 11:11 UTC, anthonydillon commented on templates/gaming/index.html
> +      <button href="/#request-form"  class="p-button--positive">Get in touch</button>
Sorry it looks like there is an contact us page: https://anbox-cloud.io/contact-us

2021-05-19 11:11 UTC, anthonydillon commented on templates/telco/index.html
> +                    <button class="p-button--positive">Get in touch</button>
Same here, can link to https://anbox-cloud.io/contact-us

2021-05-20 10:29 UTC, spencerbygraves commented
@petesfrench can we try a couple of changes please.

Can you update the second section as below. The first paragraph is h4.

![image](https://user-images.githubusercontent.com/9105999/118963273-3019e580-b95e-11eb-8230-776d6fd9abce.png)

For the last "Stream Android games" section, can you use h2 for the title, and add `is-bordered` to the strip please.

Thanks

2021-05-20 10:40 UTC, anthonydillon requested changes
I think you must have forgotten to commit the telco changes as I don't see the comments addressed. Also a few new requests

2021-05-20 10:40 UTC, anthonydillon commented on templates/gaming/index.html
> +        loading="auto"
Should be lazy loading for all images below the hero/top strip

2021-05-20 10:40 UTC, anthonydillon commented on templates/gaming/index.html
> +      <button href="/contact-us"  class="p-button--positive">Get in touch</button>
```suggestion
      <a href="/contact-us"  class="p-button--positive">Get in touch</a>
```

2021-05-20 10:40 UTC, anthonydillon commented on templates/telco/index.html
> +                    The 5G mobile <br>subscriber experience
This was not addressed

2021-05-20 10:40 UTC, anthonydillon commented on templates/telco/index.html
> +                        loading="auto"
Should be lazy

2021-05-21 10:35 UTC, spencerbygraves commented
Thanks @petesfrench, can you please make the hr in the second section the width of the grid only (above the 3 illustrations).

Thanks.

2021-05-21 10:37 UTC, anthonydillon requested changes
Few comments remaining from the previous review.

2021-05-21 10:37 UTC, anthonydillon commented on templates/gaming/index.html
> +      <button href="/contact-us"  class="p-button--positive">Get in touch</button>
Still need to do this

2021-05-21 10:37 UTC, anthonydillon commented on templates/gaming/index.html
> +        loading="auto"
This comment too

2021-05-25 13:39 UTC, anthonydillon requested changes
Some requests in the code.

2021-05-25 13:39 UTC, anthonydillon commented on templates/gaming/index.html
> +  </div>
This seems to have some misaligned indentation. Would you reindent please.

2021-05-25 13:39 UTC, anthonydillon commented on templates/gaming/index.html
> +      <div class="col-4 u-hide--small">
You don't need `u-hide--small` on each column but move it up to the parent `p-strip`

2021-05-25 13:39 UTC, anthonydillon commented on templates/telco/index.html
> +    <div class="row">
You have nested rows here. Can you remove this div

2021-05-25 13:39 UTC, anthonydillon commented on templates/telco/index.html
> +      </p>
These elements are outside of a column. I believe they should be contained in the `col-7` above.

2021-05-25 13:39 UTC, anthonydillon commented on templates/telco/index.html
> +    <div class="col-4 u-hide--small">
Move this `u-hide--small` to the row as we want the entire row hidden on small screens.

2021-05-25 13:39 UTC, anthonydillon commented on templates/telco/index.html
> +    <div class="col-5">
This could be a 6 col

2021-05-25 13:48 UTC, spencerbygraves commented
@petesfrench I don't see the change I requested, has the demo been updated? Thanks.

2021-05-25 15:57 UTC, petesfrench commented
> @petesfrench I don't see the change I requested, has the demo been updated? Thanks.

Hi Spencer, sorry I think you should be able to see it now.

2021-05-25 19:27 UTC, anthonydillon approved these changes
LGTM :+1: thanks for the changes.

2021-05-26 09:23 UTC, merged