Add appliance and deploy button linking to AWS
canonical-web-and-design/anbox-cloud.io pull request #186
Opened 2021-07-29 15:24 UTC by morphis

## Done

Add Anbox Cloud Appliance to the variant table with deploy button linking to AWS marketplace

I had to use a contextual menu as we have two different marketplace listings we need to link to: one for Arm and one for x86. Using two buttons felt wrong. Open for suggestions on how to do better. JS code is taken from the vanilla documentation.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

n/a

## Screenshots

![website-deploy-appliance](https://user-images.githubusercontent.com/433752/127519582-b07b6cbd-f229-4d19-ad80-3c1661c31efa.png)

2021-07-29 15:25 UTC, morphis commented
@bethcollins92 @SirSamTumless This is adding the left out column to the table from the copy doc as we're getting ready to push the PR fairly soon. Rollout should be still coordinated so we don't push this live before the PR.

2021-07-30 07:57 UTC, bethcollins92 commented
Thanks @morphis, could you link the PR when you have it? We can block this PR until the other is ready to go :)

2021-07-30 10:43 UTC, morphis commented
@bethcollins92 ah sorry, I mixed acronyms here. I meant PR as in press release rather than pull request. This pull request here can go as is but should not go live before the press release is out.

2021-07-30 11:32 UTC, bethcollins92 commented
@morphis no probs! Here is the demo https://anbox-cloud-io-186.demos.haus/ for the designer to review

2021-07-30 11:40 UTC, bethcollins92 commented
@spencerbygraves could you take a quick look please and see if this is ok? Thanks!

2021-08-02 09:06 UTC, spencerbygraves commented
@bethcollins92 I think it's ok to use a contextual menu with an icon button. I would suggest having the arrow on the right of the text.

https://vanillaframework.io/docs/examples/patterns/contextual-menu/default
https://vanillaframework.io/docs/examples/patterns/buttons/icon

2021-08-02 10:50 UTC, bethcollins92 requested changes
Looking good @morphis thanks for doing this! After speaking to @spencerbygraves could you please making the following small adjustments:
- use `p-button--neutral` instead of `p-button--positive`
- move the chevron to the right
- remove the `is-light` class on the chevron.

Any questions let me know, thanks!

2021-08-02 10:50 UTC, bethcollins92 commented on templates/index.html
> +                  <button class="p-button--positive p-contextual-menu__toggle has-icon" aria-controls="menu-3"
```suggestion
                  <button class="p-button--neutral p-contextual-menu__toggle has-icon" aria-controls="menu-3"
```

2021-08-02 10:50 UTC, bethcollins92 commented on templates/index.html
> +                          <i class="p-icon--chevron-down is-light p-contextual-menu__indicator"></i><span>Deploy on AWS</span>
```suggestion
                          <span>Deploy on AWS</span><i class="p-icon--chevron-down p-contextual-menu__indicator"></i>
```

2021-08-02 13:37 UTC, morphis commented
@bethcollins92 Thanks a lot for the guidance! All changes are done. Looks like this 

![website-appliance](https://user-images.githubusercontent.com/433752/127870563-a22a247f-3068-4e88-98ad-2460bf65de13.png)

2021-08-03 07:38 UTC, bethcollins92 commented
@spencerbygraves could you take a look please? https://anbox-cloud-io-186.demos.haus/

2021-08-03 13:08 UTC, spencerbygraves commented
@bethcollins92 @morphis 👍

2021-08-03 13:17 UTC, bethcollins92 approved these changes
Looking good! Just a class to add to those links (apologies, missed it first time round) and it's good to go whenever you're ready 👍🏼

2021-08-03 13:17 UTC, bethcollins92 commented on templates/index.html
> +                      <a href="https://aws.amazon.com/marketplace/pp/prodview-3lx6xyaapstz4" class="p-contextual-menu__link">on x86</a>
```suggestion
                      <a href="https://aws.amazon.com/marketplace/pp/prodview-3lx6xyaapstz4" class="p-contextual-menu__link p-link--external">on x86</a>
```

2021-08-03 13:17 UTC, bethcollins92 commented on templates/index.html
> +                      <a href="https://aws.amazon.com/marketplace/pp/prodview-aqmdt52vqs5qk" class="p-contextual-menu__link">on Arm</a>
```suggestion
                      <a href="https://aws.amazon.com/marketplace/pp/prodview-aqmdt52vqs5qk" class="p-contextual-menu__link p-link--external">on Arm</a>
```

2021-08-05 10:18 UTC, bethcollins92 commented
@morphis thank you!

2021-08-24 08:38 UTC, SirSamTumless commented
@morphis Any news on this?

2021-08-25 09:58 UTC, carkod commented
> @morphis Any news on this?

I think we should ask @bethcollins92 is this ready to go? can we remove the blocked and don't merge labels?

2021-08-25 10:35 UTC, bethcollins92 commented
> > @morphis Any news on this?
> 
> I think we should ask @bethcollins92 is this ready to go? can we remove the blocked and don't merge labels?

We are waiting for @morphis to say it's ready to go as it's waiting on a press release

2021-09-07 13:17 UTC, morphis commented
@bethcollins92 @SirSamTumless as discussed on Mattermost, this is ready to be published now as the PR just went live.

2021-09-07 13:23 UTC, merged