WIP - Update-marketo-endpoint
canonical-web-and-design/anbox-cloud.io pull request #221
Opened 2022-01-07 13:15 UTC by minkyngkm

## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8043/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

2022-01-07 13:15 UTC, webteam-app commented
Demo starting at https://anbox-cloud-io-221.demos.haus

2022-01-10 22:34 UTC, anthonydillon requested changes
Do we need the `formValidation.js ` script at all anymore if we are posting directly to ubuntu.com?

2022-01-11 09:13 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing! Yes, it works without `formValidation.js`. I have just removed that file.

2022-01-11 12:44 UTC, anthonydillon approved these changes
Great thanks :+1:

2022-01-11 13:27 UTC, merged